/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.Cryptek;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class DownpourTest {
    @Test void appHasAGreeting() {
        Downpour classUnderTest = new Downpour();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
