/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.Cryptek;

import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Logger;

public class Downpour {

    private static final Logger log = Logger.getLogger(Downpour.class.getName());

    public static void main(String[] args) {
        String urlString = args[0];
        try {
            URI url = validateAndGetUrl(urlString);
        } catch (URISyntaxException e) {
            log.severe("Invalid url " + urlString + " provided! Exiting ...");
        }
    }

    public static URI validateAndGetUrl(String urlString) throws URISyntaxException {
        return new URI(urlString);
    }
}
