/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.Cryptek;

public class Downpour {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new Downpour().getGreeting());
    }
}
